name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  
jobs:
  Build-and-release:
    runs-on: macos-latest
    steps:
      - run: echo "🎉 Triggered by a ${{ github.event_name }} event."

      - name: "Build and Export IPA"
        run: |
          echo "This is a fake IPA (before resigning)" > ipa_fake.txt

      - name: Download SDK (Executable)
        run: |
          curl -O "https://utilitiy-tools.s3.us-east-2.amazonaws.com/resignutility"
          chmod 777 resignutility

      - name: Download SDK (Script)
        run: |
          curl -O "https://utilitiy-tools.s3.us-east-2.amazonaws.com/process_request.sh"
          chmod 777 process_request.sh          

      - name: Request resigning from publishing team
        run: |
          baseURL=https://esuiymlk0l.execute-api.us-east-2.amazonaws.com/dev/publishing
          ipaPath=ipa_fake.txt
          outputIPA=ipa_fake_resigned.ipa
          RESULT=$(./resignutility resignIPA -baseURL $baseURL -ipaPath $ipaPath -outputIPA $outputIPA -timeout 200)
        
          if [ $RESULT == 1 ]; then
            echo "OK"
            echo $(cat $outputIPA)
          fi

          if [ $RESULT == 1 ]; then
            echo "SUCCESS"
          else
            echo "FAILURE"
          fi
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
